package xyz.znix.xftl.devutil

import org.jdom2.Comment
import org.jdom2.Document
import org.jdom2.Element
import org.jdom2.output.Format
import org.jdom2.output.LineSeparator
import org.jdom2.output.XMLOutputter
import org.lwjgl.BufferUtils
import org.newdawn.slick.opengl.PNGDecoder
import xyz.znix.xftl.Constants.ROOM_SIZE
import xyz.znix.xftl.Datafile
import xyz.znix.xftl.f
import xyz.znix.xftl.math.ConstPoint
import xyz.znix.xftl.math.Direction
import xyz.znix.xftl.math.IPoint
import xyz.znix.xftl.rendering.Color
import java.nio.ByteBuffer
import java.nio.file.Files
import java.nio.file.Path

/**
 * This builds an XML file that, for all the interior images, says what
 * sides are blocked on them and thus can't fit a door.
 *
 * This is used by the editor to pick suitable interior graphics,
 * via [xyz.znix.xftl.hangar.RoomImageMeta].
 */
object BakeRoomImageMeta {
    @JvmStatic
    fun main(args: Array<String>) {
        val df = Datafile.createWithDefaultPath()
        val doc = Document(Element("roomImages"))

        val commentStr = "This file was generated by the BakeRoomImageMeta class, DO NOT MODIFY BY HAND!"
        doc.addContent(0, Comment(commentStr))

        // Sort the files to make the output XML easier to read, so you can find
        // any given image quickly.
        val files = df.getAllFiles().sortedBy { it.name }

        for (file in files) {
            if (!file.name.startsWith("img/ship/interior/room_"))
                continue

            // Read in the pixel data
            df.open(file).use { stream ->
                // Get a pointer to the image memory
                require(file.name.endsWith(".png"))
                val decoder = PNGDecoder(stream)
                val stride = decoder.width * 4
                val pixels = BufferUtils.createByteBuffer(stride * decoder.height)
                decoder.decode(pixels, stride, PNGDecoder.RGBA)

                val elem = Element("image")
                elem.setAttribute("path", file.name)
                ImageProcessor(decoder, pixels, stride).processImage(elem)
                doc.rootElement.addContent(elem)
            }
        }

        val xmlOutput = XMLOutputter(Format.getPrettyFormat().apply {
            // Match the Kotlin indentation
            indent = "    "

            // Don't use CRLF on Linux
            lineSeparator = LineSeparator.SYSTEM.value()
        })
        val xml = xmlOutput.outputString(doc)
        println(xml)

        if (args.contains("--save")) {
            val path = Path.of("src/main/resources/baked/editor-door-data.xml")
            Files.writeString(path, xml, Charsets.UTF_8)
        }
    }

    private class ImageProcessor(decoder: PNGDecoder, val pixels: ByteBuffer, val stride: Int) {
        val imageSize = ConstPoint(decoder.width, decoder.height)
        val cellSize = imageSize.divideTruncate(ROOM_SIZE.f)

        fun processImage(elem: Element) {
            elem.setAttribute("width", cellSize.x.toString())
            elem.setAttribute("height", cellSize.y.toString())

            // Make sure the image size is grid-aligned.
            require(imageSize == cellSize * ROOM_SIZE)

            // Check for gaps where doors can go on the top side
            for (x in 0 until cellSize.x) {
                processEdge(elem, ConstPoint(x, 0), false)
            }

            // Bottom
            for (x in 0 until cellSize.x) {
                processEdge(elem, ConstPoint(x, cellSize.y), false)
            }

            // Left
            for (y in 0 until cellSize.y) {
                processEdge(elem, ConstPoint(0, y), true)
            }

            // Right
            for (y in 0 until cellSize.y) {
                processEdge(elem, ConstPoint(cellSize.x, y), true)
            }
        }

        private fun processEdge(elem: Element, cell: ConstPoint, isVertical: Boolean) {
            checkDoorSlot(elem, cell, isVertical)
            checkComputerSlot(elem, cell, isVertical)
        }

        private fun checkDoorSlot(elem: Element, cell: ConstPoint, isVertical: Boolean) {
            val x = cell.x * ROOM_SIZE
            val y = cell.y * ROOM_SIZE

            // Allow the outsides of the door to overlap the image, that's what
            // the Kestral's shields system does.
            val overlap = 1

            if (isVertical) {
                if (hasPixelInBlock(x - 3, y + 7 + overlap, 6, 21 - overlap * 2))
                    return
            } else {
                if (hasPixelInBlock(x + 7 + overlap, y - 3, 21 - overlap * 2, 6))
                    return
            }

            val newElem = Element("doorway")
            newElem.setAttribute("x", cell.x.toString())
            newElem.setAttribute("y", cell.y.toString())
            newElem.setAttribute("vertical", isVertical.toString())
            elem.addContent(newElem)
        }

        private fun checkComputerSlot(elem: Element, cell: ConstPoint, isVertical: Boolean) {
            // Guess where computer slots are based on their screen colours

            val x = cell.x * ROOM_SIZE
            val y = cell.y * ROOM_SIZE

            val matchColour = Color(94, 129, 127)

            val colourCount = if (isVertical) {
                countPixelColour(x - 10, y + 10, 20, 15, matchColour)
            } else {
                countPixelColour(x + 10, y - 10, 15, 20, matchColour)
            }

            if (colourCount < 15)
                return

            val pos: IPoint
            val dir: Direction

            // The position is one past the bounds for the right and bottom edges.
            // Convert this into a position-and-direction.
            when {
                cell.x == 0 && isVertical -> {
                    pos = cell
                    dir = Direction.LEFT
                }
                cell.y == 0 && !isVertical -> {
                    pos = cell
                    dir = Direction.UP
                }
                isVertical -> {
                    pos = cell - ConstPoint(1, 0)
                    dir = Direction.RIGHT
                }
                else -> {
                    pos = cell - ConstPoint(0, 1)
                    dir = Direction.DOWN
                }
            }

            val newElem = Element("computer")
            newElem.setAttribute("x", pos.x.toString())
            newElem.setAttribute("y", pos.y.toString())
            newElem.setAttribute("dir", dir.toString())
            elem.addContent(newElem)
        }

        private fun hasPixelInBlock(x: Int, y: Int, width: Int, height: Int): Boolean {
            for (py in y until y + height) {
                for (px in x until x + width) {
                    if (getPixel(px, py).a != 0f)
                        return true
                }
            }
            return false
        }

        private fun countPixelColour(x: Int, y: Int, width: Int, height: Int, toMatch: Color): Int {
            var count = 0
            for (py in y until y + height) {
                for (px in x until x + width) {
                    if (getPixel(px, py) == toMatch)
                        count++
                }
            }
            return count
        }

        private fun getPixel(x: Int, y: Int): Color {
            // It's easier to just ignore out-of-bound pixels than make sure
            // we're always using in-bound positions.
            if (x < 0 || y < 0)
                return Color.transparent
            if (x >= imageSize.x || y >= imageSize.y)
                return Color.transparent

            val index = x * 4 + y * stride

            // The 3rd byte is alpha, if it's non-zero consider the pixel occupied
            return Color(
                pixels[index + 0].toInt() and 0xff,
                pixels[index + 1].toInt() and 0xff,
                pixels[index + 2].toInt() and 0xff,
                pixels[index + 3].toInt() and 0xff
            )
        }
    }
}
