/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.znix.xftl;

import org.newdawn.slick.AppGameContainer;
import org.newdawn.slick.GameContainer;
import org.newdawn.slick.SlickException;
import xyz.znix.xftl.game.SlickGame;

import java.io.File;
import java.io.FileNotFoundException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws FileNotFoundException, SlickException {
        Datafile df = new Datafile(new File("/home/znix/Static/Games/FTL-linux/data/ftl.dat"));

        // TODO automatic extraction
        if (System.getProperty("org.lwjgl.librarypath") == null)
            System.setProperty("org.lwjgl.librarypath", new File("natives").getAbsolutePath());

        // Enable stenciling support
        GameContainer.enableStencil();

        AppGameContainer appgc;
        appgc = new AppGameContainer(new SlickGame(df));
        appgc.setTargetFrameRate(120);
        appgc.setDisplayMode(1024, 768, false);
        appgc.start();
    }
}
