/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.znix.xftl;

import xyz.znix.xftl.game.InGameState;

public class App {
    public static void main(String[] args) {
        Utils.INSTANCE.startSlick(InGameState::new);
    }
}
