package xyz.znix.xftl.savegame

/**
 * ObjectRefs is a system for producing strings that can identify
 * another object that's been serialised to XML.
 *
 * This is the version used for serialisation,
 * use [RefLoader] for deserialisation.
 */
class ObjectRefs {
    private val objectIds = HashMap<Any, String>()
    private val parent: ObjectRefs?
    private val rootParent: ObjectRefs

    // Use a single counter owned by the root parent to allocate
    // IDs, which guarantees any related ObjectRefs generate
    // unique IDs.
    private var serialCounter: Int = 0

    constructor() {
        parent = null
        rootParent = this
    }

    /**
     * Create another [ObjectRefs] instance that's based on the given parent
     * instance (we can access any object stored in it), but is isolated
     * from the parent (any objects registered in this instance can't be accessed
     * from the parent, or one of its other children).
     *
     * The object IDs generated by related instances are unique with respect
     * to one other, so the resulting IDs can be deserialised without
     * regard for how the references were built.
     *
     * The motivation for using this is to prevent things from referencing
     * objects they're supposed to be isolated from, for example crew in one
     * ship referencing crew in another ship, while still being able to
     * reference that other ship.
     */
    constructor(parent: ObjectRefs) {
        this.parent = parent
        rootParent = parent.rootParent
    }

    fun register(obj: Any?, prefix: String) {
        // Registering a null object is legal, to avoid having to null-check
        // objects while registering them.
        if (obj == null)
            return

        // Prevent an object from being registered twice under different IDs.
        if (lookup(obj) != null) {
            throw IllegalArgumentException("Cannot re-register object $obj")
        }

        // Pick a unique number to avoid duplicate IDs
        val serialNumber = rootParent.serialCounter++

        val id = "$prefix:$serialNumber"
        objectIds[obj] = id
    }

    operator fun get(obj: Any?): String {
        if (obj == null)
            return "null"

        return lookup(obj) ?: throw IllegalArgumentException("Unregistered object $obj")
    }

    private fun lookup(obj: Any): String? {
        objectIds[obj]?.let { return it }

        // Recursively lookup objects
        return parent?.lookup(obj)
    }
}

/**
 * The deserialisation equivalent of [ObjectRefs].
 *
 * This works in two modes: registering and resolving.
 *
 * You can't do some registrations then some resolutions, to try
 * and prevent bugs that depend on the order things are deserialised in.
 */
class RefLoader {
    private val objectIds = HashMap<String, Any>()
    private var resolving = false

    private val resolveFunctions = ArrayList<() -> Unit>()

    fun register(obj: Any, id: String) {
        if (resolving) {
            throw IllegalArgumentException("Cannot register object '$id' while in resolve mode!")
        }

        if (objectIds.containsKey(id)) {
            throw IllegalArgumentException("Found two objects with the same ID: '$id'")
        }

        objectIds[id] = obj
    }

    fun switchToResolveMode() {
        resolving = true

        // Run all the callbacks that were waiting until we were able to resolve them
        for (func in resolveFunctions) {
            func()
        }
        resolveFunctions.clear()
    }

    fun <T> resolve(type: Class<T>, id: String): T? {
        if (!resolving) {
            throw IllegalArgumentException("Cannot resolve object '$id' while in registering mode!")
        }

        if (id == "null") {
            return null
        }

        val obj = objectIds[id] ?: throw IllegalStateException("Missing object for ID: '$id'")

        if (!type.isInstance(obj)) {
            throw IllegalStateException("Object id='$id' must be of type ${type.simpleName}, but it's actually of type ${obj.javaClass.simpleName}")
        }

        // This is fine as we just checked it above
        @Suppress("UNCHECKED_CAST")
        return obj as T
    }

    /**
     * Queue up a function to be run when it's possible to resolve an ID.
     */
    fun <T> asyncResolve(type: Class<T>, id: String, fn: (T?) -> Unit) {
        // This is only supposed to be used before we enter resolving mode
        if (resolving) {
            throw IllegalArgumentException("Cannot async-resolve object '$id' while in resolving mode!")
        }

        resolveFunctions += {
            val result = resolve(type, id)
            fn(result)
        }
    }
}
